# Generated by Django 5.0.4 on 2026-03-03 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Razão Social: ')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ: ')),
                ('cnpj_situacao', models.CharField(choices=[('1', 'Ativa'), ('2', 'Suspensa'), ('3', 'Inapta'), ('4', 'Baixada')], default='1', max_length=1, verbose_name='Situação: ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='Logotipo: ')),
                ('description', models.TextField(blank=True, verbose_name='Descrição: ')),
                ('cnpj_rua', models.CharField(max_length=255, verbose_name='ENdereço: ')),
                ('cnpj_muncipio', models.CharField(max_length=50, verbose_name='Municipio: ')),
                ('cnpj_estado', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('PR', 'Parana')], default='FR', max_length=2)),
                ('cnpj_cep', models.CharField(max_length=9, verbose_name='CEP: ')),
                ('cnpj_cnae_principal', models.CharField(max_length=9, verbose_name='CNAE Principal: ')),
                ('cpf_responsavel_principal', models.CharField(max_length=11, verbose_name='CPF Responsável: ')),
                ('cpf_responsavel_socio', models.CharField(blank=True, default='', max_length=11, verbose_name='CPF Sócio: ')),
                ('opcao_mei', models.BooleanField(default=False, verbose_name='Opção MEI: ')),
                ('opcao_simples', models.BooleanField(default=False, verbose_name='Opção Simples Nacional: ')),
                ('email', models.EmailField(max_length=254, verbose_name='email: ')),
                ('telefone1', models.CharField(max_length=25, verbose_name='Telefone 1:')),
                ('telefone2', models.CharField(blank=True, default='', max_length=25, verbose_name='Telefone 2: ')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
