# Generated by Django 5.0.4 on 2026-02-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cnpj_cep',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cnpj_cnae_principal',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cnpj_estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('PR', 'Parana')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cnpj_muncipio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cnpj_rua',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cnpj_situacao',
            field=models.CharField(choices=[('1', 'Ativa'), ('2', 'Suspensa'), ('3', 'Inapta'), ('4', 'Baixada')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cpf_responsavel_principal',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='cpf_responsavel_socio',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='opcao_mei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opcao_simples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='telefone1',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='telefone2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
