# Generated by Django 5.0.4 on 2026-02-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_cnpj_cep_vendor_cnpj_cnae_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_cep',
            field=models.CharField(max_length=9, verbose_name='CEP: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_cnae_principal',
            field=models.CharField(max_length=9, verbose_name='CNAE Principal: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_muncipio',
            field=models.CharField(max_length=50, verbose_name='Municipio: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_rua',
            field=models.CharField(max_length=255, verbose_name='ENdereço: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cnpj_situacao',
            field=models.CharField(choices=[('1', 'Ativa'), ('2', 'Suspensa'), ('3', 'Inapta'), ('4', 'Baixada')], default='1', max_length=1, verbose_name='Situação: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Razão Social: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cpf_responsavel_principal',
            field=models.CharField(max_length=11, verbose_name='CPF Responsável: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cpf_responsavel_socio',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='CPF Sócio: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='Logotipo: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opcao_mei',
            field=models.BooleanField(default=False, verbose_name='Opção MEI: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opcao_simples',
            field=models.BooleanField(default=False, verbose_name='Opção Simples Nacional: '),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='telefone1',
            field=models.CharField(max_length=25, verbose_name='Telefone 1:'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='telefone2',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Telefone 2: '),
        ),
    ]
