# Generated by Django 5.0.4 on 2026-03-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Produto; ')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug: ')),
                ('description', models.TextField(blank=True, verbose_name='Descrição: ')),
                ('name_brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da Marca: ')),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fabricante: ')),
                ('model_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Modelo: ')),
                ('name_model_product', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome do Modelo: ')),
                ('color_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor: ')),
                ('inmetro_register', models.CharField(blank=True, max_length=30, null=True, verbose_name='Registro no INMETRO: ')),
                ('part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Peça: ')),
                ('special_features_product', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caracteristicas Especiais: ')),
                ('unit_number_product', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Unidades: ')),
                ('power_voltage_product', models.CharField(blank=True, max_length=15, null=True, verbose_name='Voltagem: ')),
                ('power_watts_product', models.CharField(blank=True, max_length=15, null=True, verbose_name='Potência em Watts: ')),
                ('type_energy_source_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Fonte: ')),
                ('batteries_included', models.BooleanField(default=False, verbose_name='Baterias Inclusas: ')),
                ('cells_batteries', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celulas de Baterias: ')),
                ('works_batteries', models.BooleanField(default=False, verbose_name='Funciona com baterias: ')),
                ('diameter_product', models.CharField(blank=True, max_length=25, null=True, verbose_name='Diametro do Produto: ')),
                ('package_dimensions', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimensões do Pacote: ')),
                ('type_material_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Material: ')),
                ('contains_liquid', models.BooleanField(default=False, verbose_name='Contêm Líquido: ')),
                ('asin_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código ASIN: ')),
                ('ean_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código EAN: ')),
                ('ncm', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código NCM: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto: ')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque: ')),
                ('active', models.BooleanField(default=True, verbose_name='Produto Ativo: ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Categoria: ')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Vendedor: ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
