# Generated by Django 5.0.4 on 2026-03-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='marketplace_fee',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Comissão do Marketplace (%)'),
        ),
    ]
